evaluation_results_path: evaluation_outputs
dataset:
  kaggle_dataset_name: uraninjo/augmented-alzheimer-mri-dataset
  input_data_subpath: AugmentedAlzheimerDataset
  output_data_path: data/augmented_alzheimer
  random_seed: 42
  test_size: 0.1
  validation_size: 0.2
trainer:
  max_epochs: 10
  patience: 5
  batch_size: 32
model:
  _target_: models.dummy_model.SimpleCNN
  learning_rate: 0.001
