name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies with Poetry
        run: poetry install --no-root --no-interaction --no-ansi

    #   - name: Set up DVC
    #     uses: iterative/setup-dvc@v3

    #   - name: DVC pull
    #     run: dvc pull --quiet

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure

    #   - name: Run tests
    #     run: poetry run pytest --maxfail=1 --disable-warnings -q
